# Generated by Django 4.0.3 on 2022-03-27 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('useremail', models.EmailField(db_column='USEREMAIL', max_length=200, unique=True)),
                ('username', models.CharField(db_column='USERNAME', max_length=200, primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='FIRSTNAME', max_length=200)),
                ('middlename', models.CharField(db_column='MIDDLENAME', max_length=200)),
                ('lastname', models.CharField(db_column='LASTNAME', max_length=200)),
                ('address', models.TextField(db_column='ADDRESS', max_length=500)),
                ('phone', models.IntegerField(db_column='PHONE')),
                ('age', models.IntegerField(db_column='AGE')),
                ('lga', models.CharField(db_column='L.G.A', max_length=200)),
                ('datereg', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registered_users',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
