# Generated by Django 4.0.3 on 2022-03-29 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unenndito_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='posts',
        ),
    ]
